//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManagementSystemAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Last_name { get; set; }
        public string Address { get; set; }
        public string Registration_date { get; set; }
        public string Telephone { get; set; }
        public string City { get; set; }
        public string Postal_Code { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Owed_money { get; set; }
        public string Domain { get; set; }
        public string Gender { get; set; }
        public bool Status { get; set; }
        public string Business_type { get; set; }
        public string Business_name { get; set; }
        public string Product_name { get; set; }
        public string Picture_url { get; set; }
        public string Country { get; set; }
        public string Cell { get; set; }
        public string How_much { get; set; }
        public string Note { get; set; }
    }
}
